### PR TITLE
Restart crond when timezone is changed

### PR DESCRIPTION
**Pull request by torrentalle**
As mentioned in isse #15 , as per https://docs.ansible.com/ansible/timezone_module.html#synopsis, it is recommended to restart crond if the timezone is changed.

This fix detect if cron service is running and then restarts it if needed.

### CODE REVIEW

**Comment by torrentalle** [comment]
Travis build job for Debian fails when molecule converge tries to download packages

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404

**Comment by torrentalle** [comment]
After making new empty commit. Travis build finisshed successfully

**Comment by xescab** [comment]
Hey! This fix looks pretty awesome. @geerlingguy, could you please take a look at this fix and merge it in master? Thanks!

**Comment by geerlingguy** [comment]
This has been rebased into #68.

**Pull request closed without merging**
