### PR TITLE
Create Rocky.yml

### PR DESCRIPTION
**Pull request by rhryniewicz20**
create vars for rocky

### CODE REVIEW

**Comment by geerlingguy** [comment]
Rocky Linux should report `"ansible_os_family": "RedHat",` though — is it not working for you?

**Comment by cblack34** [comment]
We have this problem because we use a version of ansible that predates rocky. 

We confirmed the newer versions work.

**Comment by geerlingguy** [comment]
@cblack34 - What version is that? I have set the minimum supported version of Ansible to 2.10 because supporting older versions can make for some headaches... https://github.com/geerlingguy/ansible-role-ntp/blob/master/meta/main.yml#L10

**Comment by cblack34** [comment]
@geerlingguy I believe it is 2.9. 

We tried with the latest and confirmed it works there, but we did not try with any of the intervening versions.

**Comment by rhryniewicz20** [comment]
Correct, AWX 11.2 and ansible 2.9.9

**Comment by geerlingguy** [comment]
Yeah; I'd rather leave this as is and recommend following the role's minimum supported version guideline: https://github.com/geerlingguy/ansible-role-ntp/blob/master/meta/main.yml#L10

**Pull request closed without merging**
