### PR TITLE
Fixes service not found issue.

### PR DESCRIPTION
**Pull request by blmhemu**
In one of my armbian device, i got an issue where the timesyncd is showing in services but status is not-found. That issue is fixed.

### CODE REVIEW

**Comment by blmhemu** [comment]
@geerlingguy Can this be merged please ?

**Comment by xgin** [comment]
Related issue https://github.com/geerlingguy/ansible-role-ntp/issues/87

**Comment by RealOrangeOne** [comment]
Tested working on Debian 11.

**Comment by geerlingguy** [comment]
Happy to merge, but can anyone validate that this would not break things for those users stuck on Ansible 2.9?

**Comment by gabriel-preda-adswizz** [comment]
Tested working on Centos 8.5.

**Comment by eRadical** [comment]
Tested working on Centos 8.5.

**Comment by blmhemu** [comment]
Ideally, it should not break on previous versions, because it is and condition and we get the status property.

**Comment by geerlingguy** [comment]
Thanks for the validation! This is out in the latest release.

**Pull request merged**
