### PR TITLE
REBASED: add support for chrony on EL7

### PR DESCRIPTION
**Pull request by ogajduse**
This PR is identical with #43 by @selyx but rebased to current master.
This PR should solve #71, most likely solve #22.
If you would choose a different approach, please let me know, I will try to change it.

### CODE REVIEW

**Comment by ogajduse** [comment]
@m8ram I am happy to edit these few characters.
@geerlingguy Do you want the role to keep support for RHEL 5?

Official Red Hat's [statement](https://access.redhat.com/articles/4292401) about RHEL 5 support:

> The end of Extended Life Cycle Support is scheduled for November 30, 2020, for RHEL 5.11.

**Comment by geerlingguy** [comment]
It would be _nice_ to still support RHEL 5, but I wouldn't hold back merging this at some point on that point. Note that I still use ntp on CentOS 7... haven't yet deployed CentOS 8 in production. Can you also add a centos8 test in .travis.yml since that should presumably work with chrony?

**Comment by ogajduse** [comment]
Tests on Centos 8 passed. Error in the Debian run is infrastructure-related.

**Comment by geerlingguy** [comment]
I merged this, but changed the way it works so you can still override ntp_package and ntp_config file. Because you can still install and use `ntp` on CentOS/RHEL 7 it's important to preserve the ability for people to use this role on that OS release.

For those who wish to still use ntp on CentOS 7 instead of chronyd, they can set:

```yaml
ntp_package: ntp
ntp_config_file: /etc/ntp.conf
```

And it should work the same as before. However, since defaults are changing, I am releasing a major new version of this role.

**Pull request merged**
