### PR TITLE
add support for chrony on EL7

### PR DESCRIPTION
**Pull request by selyx**
Install and configure chronyd on RHEL/ CentOS 7.

Closes PR #22

### CODE REVIEW

**Comment by nqb** [comment]
@geerlingguy : do you plan to merge this PR ?

**Comment by XabiBeltza** [comment]
It would be helpful to at check if chronyd is enabled when ntpd is set to be enabled. If not, chronyd will disable ntpd on a restart.

**Comment by nqb** [comment]
this role could help: https://github.com/linux-system-roles/timesync

**Comment by DevKyleS** [comment]
@selyx I see there's merge conflicts now, mind addressing?

**Comment by geerlingguy** [comment]
See https://github.com/geerlingguy/ansible-role-ntp/pull/72#issuecomment-604508521

**Pull request closed without merging**
